// API GETS AND SETS
export const SET_TOKEN_DATA = 'SET_TOKEN_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_PLAYLIST_DATA = 'SET_PLAYLIST_DATA';
export const UPDATE_PLAYLIST_DATA = 'UPDATE_PLAYLIST_DATA';
export const MAKE_AND_SET_PHOTO_RESPONSE = 'MAKE_AND_SET_PHOTO_RESPONSE';

// API ERRORS:
export const SET_TOKEN_DATA_ERROR = 'SET_TOKEN_DATA_ERROR';
export const ERROR_FROM_GET_USER_DATA = 'ERROR_FROM_GET_USER_DATA';
export const SET_API_ERROR = 'SET_API_ERROR';

// UI STATES: 
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const TOGGLE_GET_PLAYLIST_LOADER = "TOGGLE_GET_PLAYLIST_LOADER";
export const TOGGLE_GET_PLAYLIST_ERROR = "TOGGLE_GET_PLAYLIST_ERROR"
export const TOGGLE_LOADING_MODAL = 'TOGGLE_LOADING_MODAL';
export const TOGGLE_SUCCESS_MODAL = 'TOGGLE_SUCCESS_MODAL';
export const TOGGLE_ERROR_MODAL = 'TOGGLE_ERROR_MODAL';
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CLEAR_SELECTED_PLAYLIST = 'CLEAR_SELECTED_PLAYLIST';